DESTINATION_TABLE = {
    ("beach", "warm"):      {"destination": "Barcelona", "rationale": "Mediterranean coast, warm summers"},
    ("beach", "hot"):       {"destination": "Athens",    "rationale": "Greek islands, hot Mediterranean climate"},
    ("beach", "mild"):      {"destination": "Barcelona", "rationale": "Mediterranean coast, pleasant mild weather"},
    ("ski", "cold"):        {"destination": "Innsbruck", "rationale": "Austrian Alps, reliable winter snow"},
    ("ski", "snowy"):       {"destination": "Innsbruck", "rationale": "Austrian Alps, excellent snow record"},
    ("ski", "mild"):        {"destination": "Innsbruck", "rationale": "Alpine resort with varied ski terrain"},
    ("city", "mild"):       {"destination": "Amsterdam", "rationale": "Vibrant city break, temperate climate"},
    ("city", "warm"):       {"destination": "Rome",      "rationale": "Historic city, warm Mediterranean weather"},
    ("city", "cold"):       {"destination": "Amsterdam", "rationale": "Cultural city with cosy winter atmosphere"},
    ("cultural", "mild"):   {"destination": "Rome",      "rationale": "Major cultural heritage sites, pleasant climate"},
    ("cultural", "warm"):   {"destination": "Athens",    "rationale": "Ancient history, Mediterranean climate"},
    ("cultural", "hot"):    {"destination": "Athens",    "rationale": "Rich ancient history, hot sunny weather"},
    ("hiking", "mild"):     {"destination": "Innsbruck", "rationale": "Alpine trails, mild summers ideal for hiking"},
    ("hiking", "warm"):     {"destination": "Barcelona", "rationale": "Coastal and mountain trails near Barcelona"},
    ("any", "warm"):        {"destination": "Barcelona", "rationale": "Versatile destination, reliably warm climate"},
    ("any", "mild"):        {"destination": "Amsterdam", "rationale": "Versatile city, temperate all year"},
    ("any", "cold"):        {"destination": "Innsbruck", "rationale": "Great winter destination in the Alps"},
    ("any", "any"):         {"destination": "Amsterdam", "rationale": "Versatile default European destination"},
}
